# Generated by Django 4.2.7 on 2023-11-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('type', models.CharField(choices=[('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('suv', 'SUV'), ('mpv', 'MPV'), ('pickup', 'Pickup'), ('coupe', 'Coupe'), ('convertible', 'Convertible'), ('wagon', 'Wagon'), ('van', 'Van'), ('truck', 'Truck'), ('hybrid', 'Hybrid'), ('electric', 'Electric'), ('crossover', 'Crossover'), ('luxury', 'Luxury'), ('sports', 'Sports'), ('muscle', 'Muscle'), ('supercar', 'Supercar'), ('exotic', 'Exotic'), ('other', 'Other')], default='other', max_length=100)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
